#---------------------------------------------------------------------------------------------#
#    __  __ _            _              _       ______                                        #
#   |  \/  (_)          | |            (_)     |  ____|                                       #
#   | \  / |_ _ __   ___| |_ ___  _ __  _  __ _| |__   ___ ___  _ __   ___  _ __ ___  _   _   #
#   | |\/| | | '_ \ / _ \ __/ _ \| '_ \| |/ _` |  __| / __/ _ \| '_ \ / _ \| '_ ` _ \| | | |  #
#   | |  | | | | | |  __/ || (_) | |_) | | (_| | |___| (_| (_) | | | | (_) | | | | | | |_| |  #
#   |_|  |_|_|_| |_|\___|\__\___/| .__/|_|\__,_|______\___\___/|_| |_|\___/|_| |_| |_|\__, |  #
#                                | |                                                   __/ |  #
#                                |_|                                                  |___/   #
#                                                                                             #
#       De gratis Economy plugin voor jouw Minetopia server - Gemaakt door TheMelvinNL        #
#                                                                                             #
#---------------------------------------------------------------------------------------------#

# Welkom in het configuratiebestand van MinetopiaEconomy
# Bij elke config optie staat een kleine uitleg om het wat makkelijker te maken
# Deze plugin is helemaal gratis, wil je toch wat voor me doen? Doneer via https://paypal.me/melvinsnijders

# Het type opslag dat je wilt gebruiken, kies uit 'JSON' of 'MYSQL'. Weet je niet wat dit is? Laat het zo staan!
# Kies MySQL als je data wilt synchroniseren met andere servers, JSON slaat losse bestanden op.
storage: JSON

mysql:
  host: localhost
  port: 3306
  database: minetopiaeconomy
  username: root
  password: password

# Kies of je oude data van andere plugins automatisch wilt migreren naar MinetopiaEconomy.
# Bij een join zal de data ingeladen worden.
# Kies uit: NONE, ESSENTIALS
# Waarschuwing! Dit wordt enkel gedaan bij NIEUWE profielen.
data-migration: NONE

# Schakel dit in om alle data te synchroniseren met een andere BungeeCord server (met dezelfde plugin).
# Dit kan alleen aangezet worden als het opslagtype MySQL is.
plugin-messaging: false