name: MinetopiaEconomy
author: Melvin Snijders (TheMelvinNL)
version: 3.0.0-SNAPSHOT
main: nl.melvinsnijders.minetopiaeconomy.MinetopiaEconomy
softdepend: [Vault]
commands:
  money:
    aliases: [geld, €]
  balancetop:
    aliases: [baltop, moneytop, geldtop]
  economy:
    aliases: [eco, economie]