name: MinetopiaEconomy
author: TheMelvinNL
version: 1.0.1
main: nl.themelvin.minetopiaeconomy.Main
softdepend: [Vault]
commands:
  money:
    aliases: [geld, €]
  balancetop:
    aliases: [baltop, moneytop, geldtop]
  economy:
    aliases: [eco, economie]